name: Deploy to AWS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.x"
          
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-northeast-1

      # - name: Copy project to EC2
      #   run: |
      #     echo "${{ secrets.EC2_PRIVATE_KEY }}" > key.pem
      #     chmod 400 key.pem
      #     rsync -avz -e "ssh -i key.pem -o StrictHostKeyChecking=no" ./ ec2-user@${{ secrets.EC2_PUBLIC_IP }}:/home/ec2-user/Chatbot/Chatbot-backend

      - name: SSH into EC2 and deploy
        run: |
          echo "${{ secrets.EC2_PRIVATE_KEY }}" > key.pem
          ssh -i key.pem -o StrictHostKeyChecking=no ec2-user@${{ secrets.EC2_PUBLIC_IP }} << 'EOF'
            cd /home/ec2-user/Chatbot/Chatbot-backend
            git pull origin main
            pip install -r requirements.txt
            sudo systemctl restart chatbot-backend
          EOF
